# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/aleksandr/PycharmProjects/Builds_Message/UI/building_notification_2.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 369)
        MainWindow.setMinimumSize(QtCore.QSize(380, 369))
        MainWindow.setMaximumSize(QtCore.QSize(380, 369))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.enter_enail = QtWidgets.QLineEdit(self.frame)
        self.enter_enail.setObjectName("enter_enail")
        self.gridLayout.addWidget(self.enter_enail, 0, 1, 1, 1)
        self.enter_enail_pass = QtWidgets.QLineEdit(self.frame)
        self.enter_enail_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.enter_enail_pass.setObjectName("enter_enail_pass")
        self.gridLayout.addWidget(self.enter_enail_pass, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.enter_path_btn = QtWidgets.QToolButton(self.groupBox_3)
        self.enter_path_btn.setObjectName("enter_path_btn")
        self.gridLayout_3.addWidget(self.enter_path_btn, 0, 1, 1, 1)
        self.enter_path_dir = QtWidgets.QLineEdit(self.groupBox_3)
        self.enter_path_dir.setObjectName("enter_path_dir")
        self.gridLayout_3.addWidget(self.enter_path_dir, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 0, 1, 1)
        self.save_reset_btn = QtWidgets.QDialogButtonBox(self.frame_2)
        self.save_reset_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.save_reset_btn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.save_reset_btn.setInputMethodHints(QtCore.Qt.ImhNone)
        self.save_reset_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.save_reset_btn.setCenterButtons(False)
        self.save_reset_btn.setObjectName("save_reset_btn")
        self.gridLayout_7.addWidget(self.save_reset_btn, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.enter_path_file = QtWidgets.QLineEdit(self.groupBox)
        self.enter_path_file.setObjectName("enter_path_file")
        self.gridLayout_2.addWidget(self.enter_path_file, 0, 0, 1, 1)
        self.sel_file_btn = QtWidgets.QToolButton(self.groupBox)
        self.sel_file_btn.setObjectName("sel_file_btn")
        self.gridLayout_2.addWidget(self.sel_file_btn, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.enter_recipients_email = QtWidgets.QLineEdit(self.groupBox_5)
        self.enter_recipients_email.setObjectName("enter_recipients_email")
        self.gridLayout_5.addWidget(self.enter_recipients_email, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_4)
        self.timeEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.timeEdit.setMaximumSize(QtCore.QSize(100, 30))
        self.timeEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.timeEdit.setStyleSheet("#timeEdit{\n"
"    font: italic 18pt \"Helvetica Neue\";\n"
"background-color: rgba(253, 96, 118, 0);\n"
"}\n"
"")
        self.timeEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.timeEdit.setWrapping(True)
        self.timeEdit.setFrame(False)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setKeyboardTracking(True)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_10.addWidget(self.timeEdit, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.start_btn = QtWidgets.QDialogButtonBox(self.frame_3)
        self.start_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.start_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout_8.addWidget(self.start_btn, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Building Notification"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Enter your email and password"))
        self.label.setText(_translate("MainWindow", "email:"))
        self.label_2.setText(_translate("MainWindow", "password:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Select log directory"))
        self.enter_path_btn.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Select log file"))
        self.sel_file_btn.setText(_translate("MainWindow", "..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Enter the recipient\'s email adress"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Build Time"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Notification"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

